remote_theme: slashformotion/jekyll-archie

# The title of your website
title: Alexander Smirnov

# The description of your website
description: >- # this means to ignore newlines until "author:"
    "A personal blog"

# Your name
author: Alexander Smirnov

# The domain of your website and the location (baseurl) of your jekyll site
## THIS IS MANDATORY
url: ""
baseurl: ""

# site wide kill switch for MathJaX
enable-math: true 
  #
# END OF THE CUSTOMIZABLE SECTION
############################################################
############################################################
pagination:
  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: true
  per_page: 5

autopages:
  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: false

jekyll-archives:
  enabled: 
    - tags
    - categories
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

feed:
  path: atom.xml

plugins:
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-archie.gemspec
  - vendor
  - node-modules
  - stuff
